version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "org.apache.maven:maven-plugin-api"
        versions: ["[0.0.0,3.9.6)"]
      - dependency-name: "org.apache.maven:maven-core"
        versions: ["[0.0.0,3.9.6)"]
