version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "org.apache.maven:maven-plugin-api"
        versions: ["*"]
      - dependency-name: "org.apache.maven:maven-core"
        versions: ["*"]
