engines:
  eslint:
    npath-complexity:
      level: 50000
  duplication:
    exclude_paths:
      - "tests/**"
    config:
      languages:
        - "java"
  markdownlint:
    exclude_paths:
      - "*.md"