name: Manual Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
