name: Run Dependabot
on:
  workflow_dispatch:
jobs:
  run-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Run Dependabot
        uses: dependabot/dependabot-core@v2
        with:
          package-ecosystem: "github-actions"
          directory: "/"
          schedule: "weekly"
      - name: Run Maven Dependabot
        uses: dependabot/dependabot-core@v2
        with:
          package-ecosystem: "maven"
          directory: "/"
          schedule: "daily"
